### ISSUE TITLE
Problem decrypting notification. Private key password is incorrect.

### ISSUE THREAD

**Issue by svillagra** [IRSgov/IDES-Data-Preparation-Dot-Net#2]
Hi! I used the IDES Data Preparation .NET project to create the package and everything worked fine. But when i'm trying to decrypt the notification, i got an error indicating the password of the private key is incorrect. But i'm sure, i'm typing the right password. Can you please help with this issue?

**Comment by DanielCrouch** [comment]
It isn't something that I have ever seen an issue with. You can take the password masking off of the password textbox using the PasswordChar property just to make sure it looks correct.

Otherwise, you may want to try removing the password from the key and see if that works. You could try using something like Keystore Explorer and it should ask you for the password as well. If it takes the password, at least that will verify what it is. And you can do a Set Password in there and either change it or leave it as a blank string.

**Comment by svillagra** [comment]
Thank you. It worked! The password i was typing initially, was actually the right password. But i downloaded "Keystore Explorer", as you recommended, i changed the password for the private key, started the process all over again, and it worked fine. I appreciate your help a lot.

**Comment by DanielCrouch** [comment]
That is very strange, but I am glad it ended up working in the end.
