### ISSUE TITLE
signature problem

### ISSUE THREAD

**Issue by Roman177** [IRSgov/IDES-Data-Preparation-Dot-Net#3]
Hello!
Firstly I want to thank you for an excellent program to help make the report.
But, unfortunately, we have the result of her work is not correct.
Surely it is not connected with the program, because in other companies its working correctly. However, we do not have any ideas about the cause of the error.
The essence of the following errors. When signing our file *** paylod.xml all the added code (both counting and key) is located in one line long 3200 characters. Therefore, when checking the file in the IRS we are notified with an code NTD.
Do you have any idea of ​​the cause of this problem and how to solve it?
Sincerely, Roman
Sorry for the poor quality of my English

**Comment by DanielCrouch** [comment]
That NTD is usually caused by prohibited characters. It may be in your XML or in the digital signature itself. If it is the digital signature, it is usually in the x509SubjectName element. Depending on your certificate, you may find that double quotes were introduced there. If that is the case, you can just remove that element. It isn't necessary for the validation in IDES.

If the digital signature looks ok, check the rest of the XML contents for prohibited characters. Remember that any apostrophe or double quote will need to be replaced with an entity reference or removed. The entire list of character restrictions is posted at http://www.irs.gov/Businesses/Corporations/FATCA-XML-Schema-Best-Practices-for-Form-8966.

**Comment by Roman177** [comment]
Thank You for answer)) I understand this things and check file for prohibited characters. No one found there. I think in my keys NTD connected with length of signature line. Usually after adding signature it looking inside xml like many lines block, but in our file its one line with 3200 characters, and  i'm sure what IRS system not pass checking by this reason. Now we try prepeare file on java version of Your app.

**Comment by DanielCrouch** [comment]
I don't think it is the length. Even our sample signed file has that same line, which is just under 2600 characters for that one. 

If you have a test signed file, you can send it over to lbi.fatca.ides@irs.gov and someone can take a look at it.

**Comment by Roman177** [comment]
Thanks a lot! I send it now, before nobody from IRS not answer to us. 
Thank You really help us)

**Comment by Roman177** [comment]
Bingo!)) We already recive answer from IRS and You was absolutle right, our x509SubjectName content prohibited character. But we cant change our private key. Can You advise us: can we change You program before compillation to exclude x509SubjectName stringe from Paylod??

**Comment by DanielCrouch** [comment]
I know this is closed, but just in case anyone else runs into this issue, the KeyInfo can be removed from the signature by removing or commenting out this line in the SignEnvelopingXML method in the XmlManager file. The KeyInfo is not required for IDES. It will validate the signature by using the certificate that was used for enrollment. 

signed.KeyInfo = CreateKeyInfoFromCertificate(certificate);
